### ISSUE TITLE
Track project metadata: upstream repo, downstream package targets/requests, etc

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#291]
Over on the GFD list today (2017, March 13th) I asked Marc to start tracking project upstream URLs... and this issue is a related note to track project downstream packaging targets... so I update it to the general issue and move it to the web dashboard milestone :) 

Let's use this issue to list other project metadata that we may display on the dashboard :)

* * * 
#### Original issue:

1. Add `bakery.yml` items for a buganizer IDs for various key downstreams, so that we can track the discussion of each considering making the font family available to their users, or where it is available. 

Default:

``` yaml
downstreams:
    googlefonts: False
    bugzilla.wikimedia.org: False
    debian: False
    fedora: False
    ctan: False
```

Filled in:

``` yaml
downstreams:
    googlefonts: www.google.com/fonts/specimen/Almendra
    bugzilla.wikimedia.org: False
    debian: https://packages.debian.org/sid/fonts/fonts-ebgaramond-extra
    fedora: False
    ctan: False
```
2.  add a 'Downstream Users' title and table to the end of the Summayr page that shows this data in a simple 2 col table, where if the values are URLs then link them.
