### ISSUE TITLE
overrides on the configuration file must include a mandatory "reason" field

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3470]
So that font projects properly document the reasoning behind their custom check results overrides.

Here's one possible syntax for that:

```yaml
overrides:
    com.google.fonts/check/mandatory_glyphs:
        first-glyph:
            status: FAIL
            reason: Here's why we think this is a critical problem.
        empty:
            status: INFO
            reason: And here some explanation for that other log result override.
```
