### ISSUE TITLE
Process TTF projects correctly

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#537]
Download [RhodiumRelease.zip](https://github.com/DunwichType/RhodiumLibre/releases/download/1.1.1/RhodiumLibre.zip), unzip, use this `bakery.yaml` file:

```yaml
commit: HEAD
compiler: fontforge
license: OFL.txt
process_files: [RhodiumLibre-Regular.ttf]
pyftsubset: --notdef-outline --name-IDs=* --hinting
subset: [devanagari, latin, latin-ext]
ttfautohint: -l 7 -r 28 -G 50 -x 13 -w "G" -f deva -D deva
```

and then build:

```sh
$ fontbakery-build.py --verbose bakery.yaml;
{ 
  "name": "Rhodium Libre", 
  "designer": "James Puckett", 
  "license": "OFL", 
  "visibility": "Sandbox", 
  "category": "monospace", 
  "size": 114039, 
  "fonts": [
    {
      "name": "Rhodium Libre", 
      "postScriptName": "RhodiumLibre-Regular", 
      "fullName": "Rhodium Libre", 
      "style": "normal", 
      "weight": 400, 
      "filename": "RhodiumLibre-Regular.ttf", 
      "copyright": "Copyright © 2015 by James Puckett. All rights reserved."
    }
  ], 
  "subsets": [
    "latin"
  ], 
  "dateAdded": "2015-05-08"
}
$ tree builds/d088571
builds/d088571
├── DESCRIPTION.en_us.html
├── METADATA.json
├── METADATA.yaml
├── OFL.txt
├── build.state.yaml
├── buildlog.txt
├── fontaine.txt
├── sources
│   └── RhodiumLibre-Regular.ttf
└── upstream.yaml

1 directory, 9 files

$
```
- [x] the subsets weren't passed through by those set in the bakery.yaml file
- [x] the `builds/githash/RhodiumLibre-Regular.ttf` file I expect to see, is not there.
- [x] buildlog.txt is empty
- [x] DESCRIPTION.en_us.html is `<p>TODO</p>`, the build-metadata.py script should just not print this any more
- [x] fontaine.txt is merely 2 lines:

```
  Fonts
  All fonts have the same character sets.
```
but it should contain the output of `pyfontaine --collection subsets built_font.ttf`

- [x] `upstream.yaml` and `METADATA.yaml` are full of errors, these check results should have been printed during the `—verbose` build
